theme: jekyll-theme-minimal
markdown:    kramdown
url: https://studying.vc

title: Studying Venture Capital

collections:
   articles:
      output: true
      permalink: http://studying.vc/articles/:path/:title:output_ext
   

google_analytics: UA-91646406-1

gems:
  - jekyll-seo-tag
