theme: jekyll-theme-minimal
markdown:    kramdown
url: https://studying.vc
comments: disqus

title: Studying Venture Capital

collections:
   articles:
      output: true
   

google_analytics: UA-91646406-1

gems:
  - jekyll-seo-tag
